

-- EC_11 データベースを作成
drop database if exists EC_11;

create database if not Exists ec_11;
use ec_11;

drop table if exists goods;
drop table if exists customer_info;
drop table if exists order_info;
DROP TABLE IF EXISTS CART;


-- GOODSテーブル作成
CREATE TABLE IF NOT EXISTS GOODS(
GOODS_ID INT(100) AUTO_INCREMENT,
GOODS_NAME VARCHAR(255),
STOCK INT(50),
PRICE INT,
PRIMARY KEY(GOODS_ID)
);

-- CUSTOMER_INFOテーブル作成
CREATE TABLE IF NOT EXISTS CUSTOMER_INFO(
CUSTOMER_ID INT(100)  AUTO_INCREMENT,
CUSTOMER_NAME VARCHAR(255) NOT NULL,
CUSTOMER_PASS VARCHAR(255) UNIQUE NOT NULL,
MAILAD  VARCHAR(255) NOT NULL,
POSTCODE  VARCHAR(7) NOT NULL,
ADDRESS  VARCHAR(255) NOT NULL,
TELNUMBER VARCHAR(11) NOT NULL,
REGISTER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
PRIMARY KEY(CUSTOMER_ID)
);

-- ORDER_INFOテーブル作成
CREATE TABLE IF NOT EXISTS ORDER_INFO(
CUSTOMER_ID INT,
GOODS_ID INT(100),
ORDER_COUNT INT(100),
TOTAL_AMOUNT INT,
PURCHASEDAY TIMESTAMP  DEFAULT CURRENT_TIMESTAMP(),
FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_INFO(CUSTOMER_ID),
FOREIGN KEY(GOODS_ID) REFERENCES GOODS(GOODS_ID)
);

-- CARTテーブル作成
CREATE TABLE IF NOT EXISTS CART(
NAME VARCHAR(255) NOT NULL,
GOODS_NAME VARCHAR(255) NOT NULL,
SALES_NUMBER INT(100) NOT NULL,
PRICE INT NOT NULL,
TOTAL_AMOUNT INT NOT NULL
);



-- GOODSテーブルにデータを3件 挿入
INSERT INTO GOODS(GOODS_NAME,STOCK,PRICE)VALUES("ルフィー",10,3000);

INSERT INTO GOODS(GOODS_NAME,STOCK,PRICE)VALUES("ゾロ",10,3000);

INSERT INTO GOODS(GOODS_NAME,STOCK,PRICE)VALUES("ナミ",10,3000);

INSERT INTO GOODS(GOODS_NAME,STOCK,PRICE)VALUES("ウソップ",20,4000);

INSERT INTO GOODS(GOODS_NAME,STOCK,PRICE)VALUES("サンジ",30,5000);

INSERT INTO GOODS(GOODS_NAME,STOCK,PRICE)VALUES("チョッパー",10,6000);

INSERT INTO GOODS(GOODS_NAME,STOCK,PRICE)VALUES("ロビン",10,3000);

INSERT INTO GOODS(GOODS_NAME,STOCK,PRICE)VALUES("フランキー",10,3000);

INSERT INTO GOODS(GOODS_NAME,STOCK,PRICE)VALUES("ブルック",10,3000);

INSERT INTO GOODS(GOODS_NAME,STOCK,PRICE)VALUES("エース",20,4000);

INSERT INTO GOODS(GOODS_NAME,STOCK,PRICE)VALUES("サボ",30,5000);

INSERT INTO GOODS(GOODS_NAME,STOCK,PRICE)VALUES("ジンベエ",10,6000);

INSERT INTO GOODS(GOODS_NAME,STOCK,PRICE)VALUES("ロジャー",50,9000);

INSERT INTO GOODS(GOODS_NAME,STOCK,PRICE)VALUES("アーロン",20,2000);

INSERT INTO GOODS(GOODS_NAME,STOCK,PRICE)VALUES("クロコダイル",40,10000);

INSERT INTO GOODS(GOODS_NAME,STOCK,PRICE)VALUES("ビビ",10,1000);




-- CUTOMER_INFOテーブルにサンプルデータ挿入
INSERT INTO CUSTOMER_INFO(CUSTOMER_NAME,CUSTOMER_PASS,MAILAD,POSTCODE,ADDRESS,TELNUMBER
)VALUES(
"池田","ikeda123","ikeda@ikeda.co.jp","1234567","東京都八王子市xxx","09012345678");



-- ORDER_INFOテーブルにサンプルデータの挿入
INSERT INTO ORDER_INFO(CUSTOMER_ID,GOODS_ID,ORDER_COUNT,TOTAL_AMOUNT
)VALUES(
1,1,4,12000);


-- CARTテーブルにサンプルデータ挿入
INSERT INTO CART(NAME,GOODS_NAME,SALES_NUMBER,PRICE,TOTAL_AMOUNT
)VALUES(
"MACアド","ルフィー",1,7000,7000
);

